### ISSUE TITLE
Some errors trying to download

### ISSUE THREAD

**Issue by rmvz3** [hawkkcodes/anidownloader#1]
Hi, I'm getting some errors trying to download a test episode (macOS, M1)

First I have this:

`Traceback (most recent call last):
  File "/Applications/anidownloader.py", line 227, in <module>
    viewInfoOrDL(gonnaDownload)
  File "/Applications/anidownloader.py", line 148, in viewInfoOrDL
    downloader(animeChosen)
  File "/Applications/anidownloader.py", line 201, in downloader
    downloadChapter(animeChosen, dlMenuOption)
  File "/Applications/anidownloader.py", line 177, in downloadChapter
    os.mkdir(downloadPath)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Downloaded Anime/Naruto'`

It seems it can't create directories (I have tried from other location too). If I create the folder manually, I get this error instead:

`Traceback (most recent call last):
  File "/Applications/anidownloader.py", line 227, in <module>
    viewInfoOrDL(gonnaDownload)
  File "/Applications/anidownloader.py", line 148, in viewInfoOrDL
    downloader(animeChosen)
  File "/Applications/anidownloader.py", line 201, in downloader
    downloadChapter(animeChosen, dlMenuOption)
  File "/Applications/anidownloader.py", line 182, in downloadChapter
    megaAnonLogin.download_url(downloadLink, downloadPath, chapterFilename)
  File "/usr/local/lib/python3.9/site-packages/mega/mega.py", line 640, in download_url
    return self._download_file(
  File "/usr/local/lib/python3.9/site-packages/mega/mega.py", line 658, in _download_file
    file_data = self._api_request({
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 293, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 359, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 320, in iter
    return fut.result()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 362, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mega/mega.py", line 188, in _api_request
    raise RequestError(int_resp)
mega.errors.RequestError: ETOOMANY, Too many concurrent IP addresses are accessing this upload target URL
`

There is nothing about this in the readme. Is this a temporal error, am I doing something wrong, is the script broken?

Thank you

**Comment by ishumanga** [comment]
Hi!

About the first error: it's my bad, I forgot to add a function that checks if the needed folders to stored the downloaded chapters are created.

The second error has nothing to do with the script, but with the MEGA API, which I'm not related to in any way. The only solution I can give you for it is to try to download the desired chapter later, as that error usually pops up when there's too many people trying to access a single file.

Thank you so much for sharing these errors, and I'll try to fix them ASAP.

**Comment by rmvz3** [comment]
Great, thank you!
